language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
cache: pip3
install:
  - "pip install bs4 h5py keras lxml numpy pandas Pillow pydicom requests scikit-image scipy theano tqdm"
# command to run tests
script:
  - python -W"ignore" tests/diagnostics/biovida_diagnostics_test.py
  - python -W"ignore" tests/genomics/biovida_genomics_tests.py
  - python -W"ignore" tests/images/biovida_images_tests.py
  - python -W"ignore" tests/support_tools/biovida_support_tools.py
  - python -W"ignore" tests/unification/biovida_unification_tests.py
os: "linux"
dist: "trusty"
notifications:
    on_success: never
    on_failure: never
