language: python
python:
  - "2.7.11"
  - "3.5"
# command to install dependencies
cache: pip3
install:
  - "pip install bs4 h5py keras lxml numpy pandas Pillow pydicom requests scikit-image scipy tensorflow theano tqdm"
# command to run tests
script:
  - python -W"ignore" tests/biovida_diagnostics_test.py
  - python -W"ignore" tests/biovida_genomics_tests.py
  - python -W"ignore" tests/biovida_images_tests.py
  - python -W"ignore" tests/biovida_support_tools.py
  - python -W"ignore" tests/biovida_unification_tests.py
os: "linux"
dist: "trusty"
notifications:
    on_success: never
    on_failure: never
